apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: object-store-fn
  namespace: default
spec:
  runtime: nodejs22
  secretMounts:
  - secretName: object-store-reference-binding
    mountPath: /bindings/object-store-reference-binding
  env:
    - name: SERVICE_BINDING_ROOT
      value: /bindings
  source:
    inline:
      dependencies: |
        {
          "dependencies": {
            "@sap/xsenv": "^4.2.0",
            "@aws-sdk/client-s3": "^3.799.0"
          }
        }
      source: |
        const xsenv = require('@sap/xsenv');
        const { S3Client, ListObjectsCommand } = require("@aws-sdk/client-s3");

        var services = xsenv.getServices({
          objectstore: { label: 'objectstore' },
        });

        module.exports = {
          main: async function (event, context) {
            console.log(services.objectstore)
            const client = new S3Client({
              region: services.objectstore.region,
              endPoint: services.objectstore.host,
              credentials: {
                accessKeyId: services.objectstore.access_key_id,
                secretAccessKey: services.objectstore.secret_access_key
              }
            });

            const params = {
                Bucket: services.objectstore.bucket
            };

            const putCommand = new ListObjectsCommand(params);
            client.send(putCommand).then(data => {
                return data;
            }).catch(err => {
                console.error("error ", err);
                event.extensions.response.status(500);  
                return err;
            });
          }
        }
