module-name: serverless-manager
rc-tag: v1.0.2
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/serverless-operator:v20230911-9aa18881
  - europe-docker.pkg.dev/kyma-project/prod/function-controller:v20230905-3dd37d62
  - europe-docker.pkg.dev/kyma-project/prod/function-webhook:v20230905-3dd37d62
  - europe-docker.pkg.dev/kyma-project/prod/tpi/registry:2.8.1-1b099a1d
  - europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs16:v20230831-fb331fc0
  - europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs18:v20230831-fb331fc0
  - europe-docker.pkg.dev/kyma-project/prod/function-runtime-python39:v20230906-8690735f
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"