module-name: serverless
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/serverless-operator:1.2.0
  - europe-docker.pkg.dev/kyma-project/prod/function-controller:v20231123-a7c66276
  - europe-docker.pkg.dev/kyma-project/prod/function-build-init:v20231123-a7c66276
  - europe-docker.pkg.dev/kyma-project/prod/function-webhook:v20231123-a7c66276
  - europe-docker.pkg.dev/kyma-project/prod/tpi/registry:2.8.1-1b099a1d
  - europe-docker.pkg.dev/kyma-project/prod/tpi/kaniko-executor:1.9.1-406380b9
  - europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs16:v20231113-e18796c5
  - europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs18:v20231113-e18796c5
  - europe-docker.pkg.dev/kyma-project/prod/function-runtime-python39:v20231113-e18796c5
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"