name: 'Create SAP BTP Kyma Environment'
description: 'Action for creating Kyma runtime on SAP BTP Platform'

inputs:
  btp_subaccount_name:
    description: 'btp subaccount'
    required: true
  tf_vars:
    description: '.tfvars content for terraform'
    required: true
  tf_dir:
    description: 'tf directory'
    required: true

outputs:
  btp_subaccount_id: 
    value: ${{ steps.create-btp-resources.outputs.subaccount_id }}
    description: "ID of the created subaccount"

runs:
  using: 'composite'
  steps:
    - name: Create btp resources
      id: create-btp-resources
      run: |
        cd ${{ inputs.tf_dir }}
        terraform init
        terraform apply -auto-approve -auto-approve
        echo "subaccount_id=$(terraform output -raw subaccount_id)" >> $GITHUB_OUTPUT
      shell: bash
      env:
        TF_VAR_BTP_NEW_SUBACCOUNT_NAME: ${{ inputs.btp_subaccount_name }}
        TF_VAR_BTP_NEW_SUBACCOUNT_REGION: ${{ inputs.btp_subaccount_region }}
        TF_VAR_BTP_BACKEND_URL: ${{ inputs.btp_backend_url }}
        TF_VAR_BTP_BOT_USER: ${{ inputs.btp_user }}
        TF_VAR_BTP_BOT_PASSWORD: ${{ inputs.btp_password }}
        TF_VAR_BTP_CUSTOM_IAS_TENANT: ${{ inputs.btp_idp_tenant }}
        TF_VAR_BTP_GLOBAL_ACCOUNT: ${{ inputs.btp_global_account }}
        TF_VAR_BTP_KYMA_PLAN: ${{ inputs.btp_kyma_plan }}
        TF_VAR_BTP_KYMA_REGION: ${{ inputs.btp_kyma_region }}
        
    