apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "fullname" . }}.kyma-project.io--allow-to-registry
spec:
  podSelector:
    matchLabels:
      kyma-project.io/module: {{ template "fullname" . }}
      app.kubernetes.io/name: docker-registry
  policyTypes:
  - Ingress
  ingress:
  - from:
    # - podSelector:
    #     matchLabels:
    #       serverless.kyma-project.io/managed-by: function-controller
    ports:
    - protocol: TCP
      port: {{ .Values.global.registryServicePort }}