configMapGenerator:
- name: serverlesses
  namespace: kube-public
  files:
  - general
  - form
  - list
  - details
  options:
    disableNameSuffixHash: true
    labels:
      app.kubernetes.io/name: serverlesses
      busola.io/extension: resource
      busola.io/extension-version: "0.5"