name: kk-test

on:
  workflow_dispatch:

# permissions:
#   id-token: write # This is required for requesting the JWT token
#   contents: read # This is required for actions/checkout

jobs:
  integrations:
    secrets: inherit
    uses: ./.github/workflows/_integration-tests.yaml
    with:
      image: europe-docker.pkg.dev/kyma-project/prod/serverless-operator:1.6.0
