---
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
    creationTimestamp: null
    labels:
        app.kubernetes.io/name: function-text2img
    name: function-text2img
    namespace: default
spec:
    env:
        - name: URL
          valueFrom:
            secretKeyRef:
                key: URL
                name: deepai-secret
        - name: API-KEY
          valueFrom:
            secretKeyRef:
                key: API-KEY
                name: deepai-secret
    runtime: python39
    source:
        inline:
            dependencies: requests==2.24.0
            source: "import requests\nimport os\nfrom bottle import HTTPResponse\n\ndef main(event, context):\n\n    text = event[\"extensions\"][\"request\"].params.get(\"text\")\n\n    if text:\n        url = os.getenv('URL')\n        apiKey = os.getenv('API-KEY')\n\n        print('Trying to query {} with \"{}\"'.format(url, text))\n\n        # Send request to the external service\n        response = requests.post(url, files=dict(text=text), headers={\"api-key\": apiKey})\n    \n        return response.json()\n\n    else:\n        return HTTPResponse(body={\"'text' parameter is mandatory\"}, status=400)\n\n    \n"

---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
    creationTimestamp: null
    name: function-text2img
spec:
    gateway: kyma-gateway.kyma-system.svc.cluster.local
    host: function-text2img
    rules:
        - accessStrategies:
            - handler: allow
          methods:
            - GET
          path: /.*
    service:
        name: function-text2img
        namespace: default
        port: 80

